# .github/workflows/setup_ci_cd.yml
name: Setup CI/CD Pipeline

on:
  workflow_call:
    inputs:
      cloud_providers:
        required: true
        type: string
        description: 'Comma-separated list of cloud providers to set up CI/CD for. Options: Az, Gc, Aw'
    secrets:
      AZURE_CREDENTIALS:
        required: false
      AZURE_ORG:
        required: false
      AZURE_PROJECT:
        required: false
      GOOGLE_CREDENTIALS:
        required: false
      GCP_PROJECT:
        required: false
      GCP_ZONE:
        required: false
      AWS_CREDENTIALS:
        required: false
      AWS_REGION:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  setup-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set Environment Variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_ORG: ${{ secrets.AZURE_ORG }}
          AZURE_PROJECT: ${{ secrets.AZURE_PROJECT }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          AWS_CREDENTIALS: ${{ secrets.AWS_CREDENTIALS }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "Environment variables set."

      - name: Run CI/CD Setup Script
        run: python scripts/setup_ci_cd.py "${{ inputs.cloud_providers }}"
w