[env]
  NWN_VERSION = "8152"
  NWN_ARCH = "linux-x86"

[[services]]
  internal_port = 5121
  protocol = "udp"

  [services.concurrency]
    soft_limit = 50
    hard_limit = 50

  [[services.ports]]
    handlers = ["http"]
    port = "5121"

  [[services.restart]]
    grace_period = "300s"
    interval = "15m"
    timeout = "5s"

[deploy]
  strategy = "rolling"

[[restart]]
  policy = "never"
