name: Battle of the Dragons Revived

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  app_env: "dev"
  repo_path: "battle_of_the_dragons_revived"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup OIDC AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActions-botdr-${{ github.sha }}
          aws-region: us-east-1
      - name: Set Up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Test Fly.io Connection
        run: flyctl orgs list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Set Up Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d ${{ env.repo_path }}
      - name: Set Up Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_TOKEN }}
      - name: Run Infracost
        run: infracost breakdown --path ${{ env.repo_path }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Env Bundle
        run: yarn install
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Unit Tests
        run: yarn test --detectOpenHandles
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Yarn Build
        run: yarn build
        working-directory: "${{ env.repo_path }}/web"
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Terraform Init
        run: terraform init
        working-directory: "${{ env.repo_path }}/infra"
      - name: Terraform Validate
        run: terraform validate
        working-directory: "${{ env.repo_path }}/infra"

  deploy:
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      app_env: "dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup OIDC AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActions-botdr-${{ github.sha }}
          aws-region: us-east-1
      - name: Set Up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Test Fly.io Connection
        run: flyctl orgs list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Env Bundle
        run: yarn install
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Yarn Build
        run: yarn build
        working-directory: "${{ env.repo_path }}/web"
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Terraform Init
        run: terraform init
        working-directory: "${{ env.repo_path }}/infra"
      - name: Create Terraform Workspace
        uses: terraform-actions/terraform-new-workspace@v1
        with:
          organization: "cloud-infra-projects"
          token: ${{ secrets.TF_API_TOKEN }}
          workspace: "${{ env.app_env }}-botdr"
          working-directory: "${{ env.repo_path }}/infra"
      - name: Terraform Plan
        run: terraform plan
        working-directory: "${{ env.repo_path }}/infra"
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "${{ env.repo_path }}/infra"
