name: Battle of the Dragons Revived

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  repo_path: "battle_of_the_dragons_revived"
  node_version: "20.x"
  python_version: "3.12"
  terraform_version: "1.9.8"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      app_env: "dev"
      TF_TOKEN: ${{ secrets.TF_CLOUD_TEAM_TOKEN }}
      TF_WORKSPACE: "dev-botdr"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup OIDC AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActions-botdr-${{ github.sha }}
          aws-region: us-east-1
      - name: Set Up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Test Fly.io Connection
        run: flyctl orgs list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - name: Set Up Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d ${{ env.repo_path }} --quiet
      - name: Set Up Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_TOKEN }}
      - name: Run Infracost
        run: infracost breakdown --path ${{ env.repo_path }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Env Bundle
        run: yarn install
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Unit Tests
        run: yarn test --detectOpenHandles
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Yarn Build
        run: yarn build
        working-directory: "${{ env.repo_path }}/web"
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Terraform Init
        run: terraform init
        working-directory: "${{ env.repo_path }}/infra"
      - name: Terraform Validate
        run: terraform validate
        working-directory: "${{ env.repo_path }}/infra"
      - name: Create Terraform Workspace
        uses: dflook/terraform-new-workspace@v1.44.0
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          path: "${{ env.repo_path }}/infra"
          backend_config: token=${{ secrets.TF_CLOUD_TEAM_TOKEN }}
      - name: Terraform Plan
        run: terraform plan
        working-directory: "${{ env.repo_path }}/infra"

  deploy:
    runs-on: ubuntu-latest
    needs: unit-tests
    environment:
      name: dev
    env:
      app_env: "dev"
      TF_TOKEN: ${{ secrets.TF_CLOUD_TEAM_TOKEN }}
      TF_WORKSPACE: "dev-botdr"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup OIDC AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActions-botdr-${{ github.sha }}
          aws-region: us-east-1
      - name: Set Up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Test Fly.io Connection
        run: flyctl orgs list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_API_TOKEN }}
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Env Bundle
        run: yarn install
        working-directory: "${{ env.repo_path }}/web"
      - name: Run Yarn Build
        run: yarn build
        working-directory: "${{ env.repo_path }}/web"
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: Terraform Init
        run: terraform init
        working-directory: "${{ env.repo_path }}/infra"
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: "${{ env.repo_path }}/infra"
