name: Battle of the Dragons Revived

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  repo_path: "battle_of_the_dragons_revived"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Set Up Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d ${{ env.repo_path }}
